<?php $this->widget('EExcelView',array(
        'id'=>'patient-his-grid',
        'fixedHeader' => true,
        //'responsiveTable' => true,
        'type'=>'striped bordered hover',
        'template'=>"{summary}\n{items}\n{exportbuttons}\n{pager}",
        'dataProvider'=>$visit->showPatientHis($patient_id),
        //'summaryText' =>'<p class="text-info"> Invoice Detail </p>', 
        'htmlOptions'=>array('class'=>'table-responsive panel'),
        'columns'=>array(
                array('name'=>'id',
                    'header'=>Yii::t('app','ID'),
                    'headerHtmlOptions' => array('style' => 'display:none'),
                    'htmlOptions' => array('style' => 'display:none'),
                ),
                array('name'=>'patient_id',
                    'header'=>Yii::t('app','Patient ID'),
                    'headerHtmlOptions' => array('style' => 'display:none'),
                    'htmlOptions' => array('style' => 'display:none'),
                ),                
                array('name'=>'visit_date',
                       'header'=>'Visit Date', 
                ),
                array('name'=>'display_id',
                       'header'=>'Display ID', 
                ),
                array('name'=>'sympton',
                       'header'=>'Sympton', 
                ),
                array('name'=>'observation',
                       'header'=>'Observation', 
                ),
                array('name'=>'assessment',
                       'header'=>'Assessment', 
                ),
                array('name'=>'plan',
                       'header'=>'Plan', 
                ),
        ),
)); 
?>   